import { expect, test } from "@playwright/test";

import { SripApiClient } from "./utils/api-client";
import { randomSuffix } from "./utils/auth-files";
import { ensureUiAuthenticated } from "./utils/ensure-ui-auth";
import { getSetupUserToken } from "./utils/session";

test("notifications flow: view unread notifications and mark as read", async ({ page, request }) => {
  const api = new SripApiClient(request);
  const token = await getSetupUserToken(request);
  const suffix = randomSuffix();

  const created = await api.createNotification(token, {
    event_type: "e2e_notification",
    title: `Unread Notification ${suffix}`,
    message: "Generated by Playwright"
  });

  await ensureUiAuthenticated(page);
  await page.goto("/notifications");
  await expect(page.getByTestId("notifications-table")).toContainText(`Unread Notification ${suffix}`);
  await expect(page.getByTestId("notifications-table")).toContainText("Unread");

  await api.markNotificationRead(token, created.id);
  await page.reload();
  await expect(page.getByTestId("notifications-table")).toContainText("Read");
});
